### ISSUE TITLE
Presentation checklist

### ISSUE THREAD

**Issue by frahugo** [montrealelixir/playbook#18]
Before the meet-up

- [ ] Recharge camera batteries
- [ ] Make sure AA batteries are OK in the wireless audio modules
- [ ] Each presenter tests the connection with the AV system (adapter, screen mirroring, resolution, font-size, ...)
- [ ] Each presenter makes sure night shift and notifications are disabled (OS & browsers) (see #7)
- [ ] Each presenter makes checks its energy saving preferences to make sure the display does not shut off too early
- [ ] Each presenter makes sure the font size in Terminal and other tools is optimal
- [ ] Perform sound check (mic, camera, venue AV system)
- [ ] HDMI capture test (capture, then verify content on SD card)

Before each presentation

- [ ] Install mic on presenter
- [ ] **IMPORTANT** make sure the cables are properly screwed to the receiver/transmitter units.  Otherwise, you could loose the audio when the cable move.
- [ ] Sound check
- [ ] Start HDMI capturing
- [ ] Start video recording (make sure we have portion of the displayed slides so we can sync video with HDMI capturing)
